compatibility_date = "2023-10-16"
main = "src/index.ts"
name = "r2-webdav"

compatibility_flags = ["nodejs_compat"]

# Custom domain configuration
[[routes]]
pattern = "sync.speakez.tech/*"
zone_name = "speakez.tech"

# Add R2 bucket bindings for each user
# Binding name must match: {username}_webdav_sync
[[r2_buckets]]
binding = "testuser_webdav_sync"
bucket_name = "testuser-webdav-bucket"


# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
head_sampling_rate = 1

